"""add username field on User

Revision ID: 672e654f2d0a
Revises: f38a72249f63
Create Date: 2024-01-24 20:59:09.143686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672e654f2d0a'
down_revision: Union[str, None] = 'f38a72249f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
